In [ ]:
# 행렬 연산
import numpy as np

# 데이터 구성
import pandas as pd

# 데이터 시각화
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns

# 데이터 분할: train, test
from sklearn.model_selection import train_test_split

# Scaling 클래스
from sklearn.preprocessing import StandardScaler

# 로지스틱 회귀
import statsmodels.api as sm
from statsmodels.api import Logit 

# 분류 Decision Tree
from sklearn.tree import DecisionTreeClassifier

# 분류 Random Forest
from sklearn.ensemble import RandomForestClassifier

# 분류 Gradient Boosting
from sklearn.ensemble import GradientBoostingClassifier

# 최적 모델, 파라미터 탐색
from sklearn.model_selection import GridSearchCV

# export_graphviz: 나무 구조 생성 및 저장
from sklearn.tree import export_graphviz

# graphviz : 나무 구조 시각화 (.dot 확장자 파일 불러오기 등)
import graphviz

# 분류 모델 평가 함수
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report

# 카이제곱검정
from scipy import stats
from scipy.stats import chi2_contingency

import statsmodels.formula.api as smf

from tqdm import tqdm

In [ ]:
# 데이터 구성하기
df_member = pd.read_csv('C:/Users/Administrator/Desktop/A2_유아용품/member_이탈율.csv')
df_member

In [ ]:
# 데이터 구성하기
df_sales = pd.read_csv('C:/Users/Administrator/Desktop/A2_유아용품/Sales_data.csv')
df_sales

# Sales 데이터 결합

In [ ]:
from datetime import datetime
df_sales['구매일'] = pd.to_datetime(df_sales['구매일'])
df_sales['배송시작일'] = pd.to_datetime(df_sales['배송시작일'])
df_sales['배송완료일'] = pd.to_datetime(df_sales['배송완료일'])

In [ ]:
df_sales['구매일_연도'] = df_sales['구매일'].dt.year
df_sales['구매일_월'] = df_sales['구매일'].dt.month
df_sales['구매일_일'] = df_sales['구매일'].dt.day
df_sales['구매일_요일'] = df_sales['구매일'].dt.day_name()

In [ ]:
df_sales

,주문번호,구매일,배송시작일,배송완료일,구매시월령(수정),고객번호,구매금액,결제금액,물품대분류,상품명,배송리드타임,구매일_연도,구매일_월,구매일_일,구매일_요일
0,201905052342970,2019-05-06,2019-05-07,2019-05-11,4.0,201812310749735,25800,16314,더블하트,더블하트 SofTouch 모유실감 젖꼭지 M (2입),5,2019,5,6,Monday
1,202002203424450,2020-02-20,2020-02-21,2020-02-23,14.0,201812310749735,51200,37769,팬티,NEW 하기스 맥스드라이 팬티 5단계 남아 80매(팬티형),3,2020,2,20,Thursday
2,201902282095385,2019-02-28,2019-03-01,2019-03-05,NaN,201812310749770,5610,3800,FMC,크리넥스？키즈용？화장지？3겹？27m 8롤,5,2019,2,28,Thursday
3,201905132367003,2019-05-13,2019-05-14,2019-05-16,66.0,201812310749771,59520,47922,기저귀,하기스 네이처메이드 밤부 3단계 여아 144매(밴드형),3,2019,5,13,Monday
4,201905092356247,2019-05-10,2019-05-11,2019-05-13,5.0,201812310749774,50640,39788,기저귀,하기스 에어솔솔 썸머기저귀 3단계 공용 144매(밴드형),3,2019,5,10,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199994,20200724113704-52679491210,2020-07-24,2020-07-25,2020-07-27,5.0,20200724113017315991,11700,9240,FMC,크리넥스 뽑아쓰는 키친타월 펭수에디션 140매 X 4입 (EA),3,2020,7,24,Friday
199995,20200729134816-18220910068,2020-07-29,2020-07-30,2020-08-01,NaN,20200729134409126553,3000,3000,체험팩,맘큐 허그박스,3,2020,7,29,Wednesday
199996,20200803080150-09054399128,2020-08-03,2020-08-04,2020-08-07,5.0,20200803075905757887,5900,5841,체험팩,NEW 하기스 맥스드라이 팬티 3단계 공용 20매(팬티형/체험팩) (EA),4,2020,8,3,Monday
199997,20200805171023-18783441109,2020-08-06,2020-08-07,2020-08-11,NaN,20200805170229147688,3000,3000,체험팩,맘큐 허그박스,5,2020,8,6,Thursday
199998,20200805224157-34181488371,2020-08-06,2020-08-07,2020-08-09,NaN,20200805223526494551,8500,8500,기타,[먼치킨] 멀티 젖병솔 세트,3,2020,8,6,Thursday

In [ ]:
result = df_sales.groupby(['구매일_연도','구매일_월'])['결제금액'].sum()
print(result)

구매일_연도  구매일_월
2019    1         88867985
        2        136463219
        3        161780826
        4        179559469
        5        213899693
        6        228794478
        7        291671879
        8        272403200
        9        265811765
        10       383916819
        11       258996377
        12       366535894
2020    1        313459342
        2        303402730
        3        239678575
        4        236243795
        5        139778803
        6         93831198
        7        140348130
        8         27293661
Name: 결제금액, dtype: int64

In [ ]:
df_sales['할인금액'] = df_sales['구매금액'] - df_sales['결제금액']
df_sales

,주문번호,구매일,배송시작일,배송완료일,구매시월령(수정),고객번호,구매금액,결제금액,물품대분류,상품명,배송리드타임,구매일_연도,구매일_월,구매일_일,구매일_요일,할인금액
0,201905052342970,2019-05-06,2019-05-07,2019-05-11,4.0,201812310749735,25800,16314,더블하트,더블하트 SofTouch 모유실감 젖꼭지 M (2입),5,2019,5,6,Monday,9486
1,202002203424450,2020-02-20,2020-02-21,2020-02-23,14.0,201812310749735,51200,37769,팬티,NEW 하기스 맥스드라이 팬티 5단계 남아 80매(팬티형),3,2020,2,20,Thursday,13431
2,201902282095385,2019-02-28,2019-03-01,2019-03-05,NaN,201812310749770,5610,3800,FMC,크리넥스？키즈용？화장지？3겹？27m 8롤,5,2019,2,28,Thursday,1810
3,201905132367003,2019-05-13,2019-05-14,2019-05-16,66.0,201812310749771,59520,47922,기저귀,하기스 네이처메이드 밤부 3단계 여아 144매(밴드형),3,2019,5,13,Monday,11598
4,201905092356247,2019-05-10,2019-05-11,2019-05-13,5.0,201812310749774,50640,39788,기저귀,하기스 에어솔솔 썸머기저귀 3단계 공용 144매(밴드형),3,2019,5,10,Friday,10852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199994,20200724113704-52679491210,2020-07-24,2020-07-25,2020-07-27,5.0,20200724113017315991,11700,9240,FMC,크리넥스 뽑아쓰는 키친타월 펭수에디션 140매 X 4입 (EA),3,2020,7,24,Friday,2460
199995,20200729134816-18220910068,2020-07-29,2020-07-30,2020-08-01,NaN,20200729134409126553,3000,3000,체험팩,맘큐 허그박스,3,2020,7,29,Wednesday,0
199996,20200803080150-09054399128,2020-08-03,2020-08-04,2020-08-07,5.0,20200803075905757887,5900,5841,체험팩,NEW 하기스 맥스드라이 팬티 3단계 공용 20매(팬티형/체험팩) (EA),4,2020,8,3,Monday,59
199997,20200805171023-18783441109,2020-08-06,2020-08-07,2020-08-11,NaN,20200805170229147688,3000,3000,체험팩,맘큐 허그박스,5,2020,8,6,Thursday,0
199998,20200805224157-34181488371,2020-08-06,2020-08-07,2020-08-09,NaN,20200805223526494551,8500,8500,기타,[먼치킨] 멀티 젖병솔 세트,3,2020,8,6,Thursday,0

In [ ]:
# 데이터 구성하기
df_product = pd.read_csv('C:/Users/Administrator/Desktop/엑셀파일/Product_분류(대분류,중분류,브랜드).csv',encoding='euc-kr')
df_product

,물품대분류,상품명,물품판매량,제품단가,브랜드명,물품분류,물품중분류,기저귀 유형,기저귀 단계,Age_Range
0,FC,(1+1) 좋은느낌 입는 오버나이트 대형 8개입,15,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN
1,FC,(1+1) 좋은느낌 입는 오버나이트 중형 8개입,10,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN
2,FC,(1+1) 화이트 입는 오버나이트 대형 L 8개입 (EA),27,0,화이트,여성용품,생리대,NaN,NaN,NaN
3,FC,(1+1) 화이트 입는 오버나이트 중형 M 8개입 (EA),12,0,화이트,여성용품,생리대,NaN,NaN,NaN
4,FC,(핫딜위크/1+1) 좋은느낌 입는 오버나이트 대형 8개입,4,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
3043,팬티,하기스 에어솔솔 썸머팬티 6단계 여아용 68매(팬티형),4,47360,하기스,베이비용품,기저귀,팬티형,6.0,유아
3044,팬티,하기스 에어솔솔 팬티 4단계 남아용 96매(팬티형),18,71040,하기스,베이비용품,기저귀,팬티형,4.0,영아
3045,팬티,하기스 에어솔솔 팬티 4단계 여아용 96매(팬티형),17,66861,하기스,베이비용품,기저귀,팬티형,4.0,영아
3046,팬티,하기스 에어솔솔 팬티 5단계 남아용 80매(팬티형),81,68994,하기스,베이비용품,기저귀,팬티형,5.0,유아
3047,팬티,하기스 에어솔솔 팬티 5단계 여아용 80매(팬티형),34,76612,하기스,베이비용품,기저귀,팬티형,5.0,유아

In [ ]:
z2 = df_sales.groupby(by = ['상품명'])['배송리드타임'].sum()
z3 = df_sales.groupby(by = ['상품명'])['배송리드타임'].count()

total_avg_readtime = (z2 / z3).round(0)
df_product = pd.merge(df_product, total_avg_readtime, how = 'left', on = '상품명')
df_product.rename(columns={'배송리드타임':'평균 배송리드타임'},inplace=True)
df_product

,물품대분류,상품명,물품판매량,제품단가,브랜드명,물품분류,물품중분류,기저귀 유형,기저귀 단계,Age_Range,평균 배송리드타임
0,FC,(1+1) 좋은느낌 입는 오버나이트 대형 8개입,15,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN,4.0
1,FC,(1+1) 좋은느낌 입는 오버나이트 중형 8개입,10,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN,4.0
2,FC,(1+1) 화이트 입는 오버나이트 대형 L 8개입 (EA),27,0,화이트,여성용품,생리대,NaN,NaN,NaN,4.0
3,FC,(1+1) 화이트 입는 오버나이트 중형 M 8개입 (EA),12,0,화이트,여성용품,생리대,NaN,NaN,NaN,3.0
4,FC,(핫딜위크/1+1) 좋은느낌 입는 오버나이트 대형 8개입,4,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...
3043,팬티,하기스 에어솔솔 썸머팬티 6단계 여아용 68매(팬티형),4,47360,하기스,베이비용품,기저귀,팬티형,6.0,유아,4.0
3044,팬티,하기스 에어솔솔 팬티 4단계 남아용 96매(팬티형),18,71040,하기스,베이비용품,기저귀,팬티형,4.0,영아,3.0
3045,팬티,하기스 에어솔솔 팬티 4단계 여아용 96매(팬티형),17,66861,하기스,베이비용품,기저귀,팬티형,4.0,영아,3.0
3046,팬티,하기스 에어솔솔 팬티 5단계 남아용 80매(팬티형),81,68994,하기스,베이비용품,기저귀,팬티형,5.0,유아,3.0
3047,팬티,하기스 에어솔솔 팬티 5단계 여아용 80매(팬티형),34,76612,하기스,베이비용품,기저귀,팬티형,5.0,유아,3.0

In [ ]:
z4 = df_sales.groupby(by = ['상품명'])['할인금액'].sum()
z5 = df_sales.groupby(by = ['상품명'])['할인금액'].count()

total_avg_sale = (z4 / z5).round(0)

df_product = pd.merge(df_product, total_avg_sale, how = 'left', on = '상품명')
df_product.rename(columns={'할인금액':'평균 할인금액'},inplace=True)
df_product

,물품대분류,상품명,물품판매량,제품단가,브랜드명,물품분류,물품중분류,기저귀 유형,기저귀 단계,Age_Range,평균 배송리드타임,평균 할인금액
0,FC,(1+1) 좋은느낌 입는 오버나이트 대형 8개입,15,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN,4.0,0.0
1,FC,(1+1) 좋은느낌 입는 오버나이트 중형 8개입,10,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN,4.0,0.0
2,FC,(1+1) 화이트 입는 오버나이트 대형 L 8개입 (EA),27,0,화이트,여성용품,생리대,NaN,NaN,NaN,4.0,0.0
3,FC,(1+1) 화이트 입는 오버나이트 중형 M 8개입 (EA),12,0,화이트,여성용품,생리대,NaN,NaN,NaN,3.0,0.0
4,FC,(핫딜위크/1+1) 좋은느낌 입는 오버나이트 대형 8개입,4,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3043,팬티,하기스 에어솔솔 썸머팬티 6단계 여아용 68매(팬티형),4,47360,하기스,베이비용품,기저귀,팬티형,6.0,유아,4.0,11103.0
3044,팬티,하기스 에어솔솔 팬티 4단계 남아용 96매(팬티형),18,71040,하기스,베이비용품,기저귀,팬티형,4.0,영아,3.0,21219.0
3045,팬티,하기스 에어솔솔 팬티 4단계 여아용 96매(팬티형),17,66861,하기스,베이비용품,기저귀,팬티형,4.0,영아,3.0,20949.0
3046,팬티,하기스 에어솔솔 팬티 5단계 남아용 80매(팬티형),81,68994,하기스,베이비용품,기저귀,팬티형,5.0,유아,3.0,21496.0
3047,팬티,하기스 에어솔솔 팬티 5단계 여아용 80매(팬티형),34,76612,하기스,베이비용품,기저귀,팬티형,5.0,유아,3.0,25318.0

In [ ]:
df_member_new = pd.read_csv('member_파생변수 생성.csv', index_col=0)
df_member_new

,고객번호,성별,결혼유무,거주지역,연령,결제등록카드,유입경로,자녀여부,평균 배송리드타임,구매횟수,재구매횟수,총구매금액,총결제금액,최종구매일,휴면지속날짜,휴면계정여부,회당 결제금액,나이대
0,201812310749735,여,기혼,인천,37.0,국민은행,인스타그램,Yes,4.0,2,1,77000,54083,2020-02-20,169,True,27041.5,30대
1,201812310749770,여,기혼,제주,33.0,국민은행,검색광고,Yes,5.0,1,0,5610,3800,2019-02-28,526,True,3800.0,30대
2,201812310749771,여,기혼,부산,32.0,하나은행,네이버블로그,Yes,3.0,1,0,59520,47922,2019-05-13,452,True,47922.0,30대
3,201812310749774,여,미혼,경남,34.0,기업은행,지인추천,No,3.5,2,1,151920,116532,2019-07-29,375,True,58266.0,30대
4,201812310749780,여,기혼,서울,32.0,신한은행,직접검색,Yes,3.0,1,0,27920,19900,2019-01-30,555,True,19900.0,30대
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67318,201912291058164,여,기혼,경기,31.0,국민은행,오픈마켓,Yes,3.0,1,0,48900,25778,2020-06-01,67,False,25778.0,30대
67319,201912291058167,여,기혼,경남,37.0,롯데카드,오픈마켓,Yes,3.0,2,1,124200,99893,2020-04-19,110,False,49946.5,30대
67320,201912291058168,여,기혼,충북,26.0,삼성카드,검색광고,Yes,3.5,4,3,211940,163234,2020-07-18,20,False,40808.5,20대
67321,201912291058169,여,기혼,경기,32.0,새마을금고,인스타그램,Yes,3.0,1,0,51000,36579,2019-12-29,222,True,36579.0,30대
67322,201912291058171,여,기혼,서울,35.0,새마을금고,인스타그램,Yes,3.0,1,0,4900,4851,2020-05-15,84,False,4851.0,30대

In [ ]:
q1 = df_sales.groupby(by = ['고객번호'])['구매일'].min()

In [ ]:
df_member_new = pd.merge(df_member_new, q1, how = 'left', on = '고객번호')
df_member_new.rename(columns={'구매일':'첫구매일'},inplace=True)

In [ ]:
df_member_new

,고객번호,성별,결혼유무,거주지역,연령,결제등록카드,유입경로,자녀여부,평균 배송리드타임,구매횟수,재구매횟수,총구매금액,총결제금액,최종구매일,휴면지속날짜,휴면계정여부,회당 결제금액,나이대,첫구매일
0,201812310749735,여,기혼,인천,37.0,국민은행,인스타그램,Yes,4.0,2,1,77000,54083,2020-02-20,169,True,27041.5,30대,2019-05-06
1,201812310749770,여,기혼,제주,33.0,국민은행,검색광고,Yes,5.0,1,0,5610,3800,2019-02-28,526,True,3800.0,30대,2019-02-28
2,201812310749771,여,기혼,부산,32.0,하나은행,네이버블로그,Yes,3.0,1,0,59520,47922,2019-05-13,452,True,47922.0,30대,2019-05-13
3,201812310749774,여,미혼,경남,34.0,기업은행,지인추천,No,3.5,2,1,151920,116532,2019-07-29,375,True,58266.0,30대,2019-05-10
4,201812310749780,여,기혼,서울,32.0,신한은행,직접검색,Yes,3.0,1,0,27920,19900,2019-01-30,555,True,19900.0,30대,2019-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67318,201912291058164,여,기혼,경기,31.0,국민은행,오픈마켓,Yes,3.0,1,0,48900,25778,2020-06-01,67,False,25778.0,30대,NaT
67319,201912291058167,여,기혼,경남,37.0,롯데카드,오픈마켓,Yes,3.0,2,1,124200,99893,2020-04-19,110,False,49946.5,30대,NaT
67320,201912291058168,여,기혼,충북,26.0,삼성카드,검색광고,Yes,3.5,4,3,211940,163234,2020-07-18,20,False,40808.5,20대,NaT
67321,201912291058169,여,기혼,경기,32.0,새마을금고,인스타그램,Yes,3.0,1,0,51000,36579,2019-12-29,222,True,36579.0,30대,NaT
67322,201912291058171,여,기혼,서울,35.0,새마을금고,인스타그램,Yes,3.0,1,0,4900,4851,2020-05-15,84,False,4851.0,30대,NaT

In [ ]:
df_member_new['최종구매일'] = pd.to_datetime(df_member_new['최종구매일'])
df_member_new['첫구매일'] = pd.to_datetime(df_member_new['첫구매일'])
print(df_member_new.dtypes)

고객번호                 object
성별                   object
결혼유무                 object
거주지역                 object
연령                  float64
결제등록카드               object
유입경로                 object
자녀여부                 object
평균 배송리드타임           float64
구매횟수                  int64
재구매횟수                 int64
총구매금액                 int64
총결제금액                 int64
최종구매일        datetime64[ns]
휴면지속날짜                int64
휴면계정여부                 bool
회당 결제금액             float64
나이대                  object
첫구매일         datetime64[ns]
dtype: object

In [ ]:
use_days = (df_member_new['최종구매일'] - df_member_new['첫구매일']).dt.days

In [ ]:
df_member_new['사이트 이용 기간'] = use_days + 1

In [ ]:
df_member_new

,고객번호,성별,결혼유무,거주지역,연령,결제등록카드,유입경로,자녀여부,평균 배송리드타임,구매횟수,재구매횟수,총구매금액,총결제금액,최종구매일,휴면지속날짜,휴면계정여부,회당 결제금액,나이대,첫구매일,사이트 이용 기간
0,201812310749735,여,기혼,인천,37.0,국민은행,인스타그램,Yes,4.0,2,1,77000,54083,2020-02-20,169,True,27041.5,30대,2019-05-06,291.0
1,201812310749770,여,기혼,제주,33.0,국민은행,검색광고,Yes,5.0,1,0,5610,3800,2019-02-28,526,True,3800.0,30대,2019-02-28,1.0
2,201812310749771,여,기혼,부산,32.0,하나은행,네이버블로그,Yes,3.0,1,0,59520,47922,2019-05-13,452,True,47922.0,30대,2019-05-13,1.0
3,201812310749774,여,미혼,경남,34.0,기업은행,지인추천,No,3.5,2,1,151920,116532,2019-07-29,375,True,58266.0,30대,2019-05-10,81.0
4,201812310749780,여,기혼,서울,32.0,신한은행,직접검색,Yes,3.0,1,0,27920,19900,2019-01-30,555,True,19900.0,30대,2019-01-30,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67318,201912291058164,여,기혼,경기,31.0,국민은행,오픈마켓,Yes,3.0,1,0,48900,25778,2020-06-01,67,False,25778.0,30대,NaT,NaN
67319,201912291058167,여,기혼,경남,37.0,롯데카드,오픈마켓,Yes,3.0,2,1,124200,99893,2020-04-19,110,False,49946.5,30대,NaT,NaN
67320,201912291058168,여,기혼,충북,26.0,삼성카드,검색광고,Yes,3.5,4,3,211940,163234,2020-07-18,20,False,40808.5,20대,NaT,NaN
67321,201912291058169,여,기혼,경기,32.0,새마을금고,인스타그램,Yes,3.0,1,0,51000,36579,2019-12-29,222,True,36579.0,30대,NaT,NaN
67322,201912291058171,여,기혼,서울,35.0,새마을금고,인스타그램,Yes,3.0,1,0,4900,4851,2020-05-15,84,False,4851.0,30대,NaT,NaN

In [ ]:
df_member_new.isnull().sum()

고객번호            0
성별              0
결혼유무            0
거주지역            0
연령              0
결제등록카드          0
유입경로            0
자녀여부            0
평균 배송리드타임       0
구매횟수            0
재구매횟수           0
총구매금액           0
총결제금액           0
최종구매일           0
휴면지속날짜          0
휴면계정여부          0
회당 결제금액         0
나이대             0
첫구매일         1787
사이트 이용 기간    1787
dtype: int64

In [ ]:
df_member_new.to_csv('member_파생변수생성.csv', encoding='utf-8-sig')

In [ ]:
df_ss = pd.read_csv('data_2.csv',index_col=0)
df_ss

,Unnamed: 0.1,물품대분류,상품명,물품판매량,제품단가,브랜드명,물품분류,물품중분류,기저귀 유형,기저귀 단계,Age_Range,평균 배송리드타임,평균 할인금액
0,0,FC,(1+1) 좋은느낌 입는 오버나이트 대형 8개입,15,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN,4.0,0.0
1,1,FC,(1+1) 좋은느낌 입는 오버나이트 중형 8개입,10,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN,4.0,0.0
2,2,FC,(1+1) 화이트 입는 오버나이트 대형 L 8개입 (EA),27,0,화이트,여성용품,생리대,NaN,NaN,NaN,4.0,0.0
3,3,FC,(1+1) 화이트 입는 오버나이트 중형 M 8개입 (EA),12,0,화이트,여성용품,생리대,NaN,NaN,NaN,3.0,0.0
4,4,FC,(핫딜위크/1+1) 좋은느낌 입는 오버나이트 대형 8개입,4,0,좋은느낌,여성용품,생리대,NaN,NaN,NaN,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3043,3043,팬티,하기스 에어솔솔 썸머팬티 6단계 여아용 68매(팬티형),4,47360,하기스,베이비용품,기저귀,팬티형,6.0,유아,4.0,11103.0
3044,3044,팬티,하기스 에어솔솔 팬티 4단계 남아용 96매(팬티형),18,71040,하기스,베이비용품,기저귀,팬티형,4.0,영아,3.0,21219.0
3045,3045,팬티,하기스 에어솔솔 팬티 4단계 여아용 96매(팬티형),17,66861,하기스,베이비용품,기저귀,팬티형,4.0,영아,3.0,20949.0
3046,3046,팬티,하기스 에어솔솔 팬티 5단계 남아용 80매(팬티형),81,68994,하기스,베이비용품,기저귀,팬티형,5.0,유아,3.0,21496.0
3047,3047,팬티,하기스 에어솔솔 팬티 5단계 여아용 80매(팬티형),34,76612,하기스,베이비용품,기저귀,팬티형,5.0,유아,3.0,25318.0

In [ ]:
df_new = df_ss.drop(['물품대분류','물품판매량','제품단가','기저귀 유형','기저귀 단계','Age_Range','평균 배송리드타임','평균 할인금액','Unnamed: 0.1'], axis=1)
df_new['단순상품명'] = df_new['브랜드명'] + '_' + df_new['물품중분류']
df_new

                                   상품명  브랜드명   물품분류 물품중분류     단순상품명
0           (1+1) 좋은느낌 입는 오버나이트 대형 8개입  좋은느낌   여성용품   생리대  좋은느낌_생리대
1           (1+1) 좋은느낌 입는 오버나이트 중형 8개입  좋은느낌   여성용품   생리대  좋은느낌_생리대
2     (1+1) 화이트 입는 오버나이트 대형 L 8개입 (EA)   화이트   여성용품   생리대   화이트_생리대
3     (1+1) 화이트 입는 오버나이트 중형 M 8개입 (EA)   화이트   여성용품   생리대   화이트_생리대
4      (핫딜위크/1+1) 좋은느낌 입는 오버나이트 대형 8개입  좋은느낌   여성용품   생리대  좋은느낌_생리대
...                                ...   ...    ...   ...       ...
3043    하기스 에어솔솔 썸머팬티 6단계 여아용 68매(팬티형)   하기스  베이비용품   기저귀   하기스_기저귀
3044      하기스 에어솔솔 팬티 4단계 남아용 96매(팬티형)   하기스  베이비용품   기저귀   하기스_기저귀
3045      하기스 에어솔솔 팬티 4단계 여아용 96매(팬티형)   하기스  베이비용품   기저귀   하기스_기저귀
3046      하기스 에어솔솔 팬티 5단계 남아용 80매(팬티형)   하기스  베이비용품   기저귀   하기스_기저귀
3047      하기스 에어솔솔 팬티 5단계 여아용 80매(팬티형)   하기스  베이비용품   기저귀   하기스_기저귀

[3048 rows x 5 columns]

In [ ]:
df_sales_new = pd.read_csv('sales_파생변수 생성.csv')
df_sales_new

,Unnamed: 0,주문번호,구매일,배송시작일,배송완료일,구매시월령(수정),고객번호,구매금액,결제금액,물품대분류,상품명,배송리드타임,구매일_연도,구매일_월,구매일_일,구매일_요일,할인금액
0,0,201905052342970,2019-05-06,2019-05-07,2019-05-11,4.0,201812310749735,25800,16314,더블하트,더블하트 SofTouch 모유실감 젖꼭지 M (2입),5,2019,5,6,Monday,9486
1,1,202002203424450,2020-02-20,2020-02-21,2020-02-23,14.0,201812310749735,51200,37769,팬티,NEW 하기스 맥스드라이 팬티 5단계 남아 80매(팬티형),3,2020,2,20,Thursday,13431
2,2,201902282095385,2019-02-28,2019-03-01,2019-03-05,NaN,201812310749770,5610,3800,FMC,크리넥스？키즈용？화장지？3겹？27m 8롤,5,2019,2,28,Thursday,1810
3,3,201905132367003,2019-05-13,2019-05-14,2019-05-16,66.0,201812310749771,59520,47922,기저귀,하기스 네이처메이드 밤부 3단계 여아 144매(밴드형),3,2019,5,13,Monday,11598
4,4,201905092356247,2019-05-10,2019-05-11,2019-05-13,5.0,201812310749774,50640,39788,기저귀,하기스 에어솔솔 썸머기저귀 3단계 공용 144매(밴드형),3,2019,5,10,Friday,10852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199994,199994,20200724113704-52679491210,2020-07-24,2020-07-25,2020-07-27,5.0,20200724113017315991,11700,9240,FMC,크리넥스 뽑아쓰는 키친타월 펭수에디션 140매 X 4입 (EA),3,2020,7,24,Friday,2460
199995,199995,20200729134816-18220910068,2020-07-29,2020-07-30,2020-08-01,NaN,20200729134409126553,3000,3000,체험팩,맘큐 허그박스,3,2020,7,29,Wednesday,0
199996,199996,20200803080150-09054399128,2020-08-03,2020-08-04,2020-08-07,5.0,20200803075905757887,5900,5841,체험팩,NEW 하기스 맥스드라이 팬티 3단계 공용 20매(팬티형/체험팩) (EA),4,2020,8,3,Monday,59
199997,199997,20200805171023-18783441109,2020-08-06,2020-08-07,2020-08-11,NaN,20200805170229147688,3000,3000,체험팩,맘큐 허그박스,5,2020,8,6,Thursday,0
199998,199998,20200805224157-34181488371,2020-08-06,2020-08-07,2020-08-09,NaN,20200805223526494551,8500,8500,기타,[먼치킨] 멀티 젖병솔 세트,3,2020,8,6,Thursday,0

In [ ]:
df_sales_new = df_sales_new.drop(['Unnamed: 0','배송시작일','배송완료일','구매시월령(수정)','구매금액','결제금액','배송리드타임','구매일_연도','구매일_월','구매일_일','구매일_요일','할인금액'], axis=1)
df_sales_new

,주문번호,구매일,고객번호,물품대분류,상품명
0,201905052342970,2019-05-06,201812310749735,더블하트,더블하트 SofTouch 모유실감 젖꼭지 M (2입)
1,202002203424450,2020-02-20,201812310749735,팬티,NEW 하기스 맥스드라이 팬티 5단계 남아 80매(팬티형)
2,201902282095385,2019-02-28,201812310749770,FMC,크리넥스？키즈용？화장지？3겹？27m 8롤
3,201905132367003,2019-05-13,201812310749771,기저귀,하기스 네이처메이드 밤부 3단계 여아 144매(밴드형)
4,201905092356247,2019-05-10,201812310749774,기저귀,하기스 에어솔솔 썸머기저귀 3단계 공용 144매(밴드형)
...,...,...,...,...,...
199994,20200724113704-52679491210,2020-07-24,20200724113017315991,FMC,크리넥스 뽑아쓰는 키친타월 펭수에디션 140매 X 4입 (EA)
199995,20200729134816-18220910068,2020-07-29,20200729134409126553,체험팩,맘큐 허그박스
199996,20200803080150-09054399128,2020-08-03,20200803075905757887,체험팩,NEW 하기스 맥스드라이 팬티 3단계 공용 20매(팬티형/체험팩) (EA)
199997,20200805171023-18783441109,2020-08-06,20200805170229147688,체험팩,맘큐 허그박스
199998,20200805224157-34181488371,2020-08-06,20200805223526494551,기타,[먼치킨] 멀티 젖병솔 세트

In [ ]:
df_sales_new = pd.merge(df_sales_new, df_new, how = 'left', on = '상품명')
df_sales_new

,주문번호,구매일,고객번호,물품대분류,상품명,브랜드명,물품분류,물품중분류,단순상품명
0,201905052342970,2019-05-06,201812310749735,더블하트,더블하트 SofTouch 모유실감 젖꼭지 M (2입),더블하트,베이비용품,수유용품,더블하트_수유용품
1,202002203424450,2020-02-20,201812310749735,팬티,NEW 하기스 맥스드라이 팬티 5단계 남아 80매(팬티형),하기스,베이비용품,기저귀,하기스_기저귀
2,201902282095385,2019-02-28,201812310749770,FMC,크리넥스？키즈용？화장지？3겹？27m 8롤,크리넥스,가정용품,휴지/티슈,크리넥스_휴지/티슈
3,201905132367003,2019-05-13,201812310749771,기저귀,하기스 네이처메이드 밤부 3단계 여아 144매(밴드형),하기스,베이비용품,기저귀,하기스_기저귀
4,201905132367003,2019-05-13,201812310749771,기저귀,하기스 네이처메이드 밤부 3단계 여아 144매(밴드형),하기스,베이비용품,기저귀,하기스_기저귀
...,...,...,...,...,...,...,...,...,...
210034,20200724113704-52679491210,2020-07-24,20200724113017315991,FMC,크리넥스 뽑아쓰는 키친타월 펭수에디션 140매 X 4입 (EA),크리넥스,가정용품,키친타올/행주,크리넥스_키친타올/행주
210035,20200729134816-18220910068,2020-07-29,20200729134409126553,체험팩,맘큐 허그박스,맘큐,베이비용품,기저귀,맘큐_기저귀
210036,20200803080150-09054399128,2020-08-03,20200803075905757887,체험팩,NEW 하기스 맥스드라이 팬티 3단계 공용 20매(팬티형/체험팩) (EA),하기스,베이비용품,기저귀,하기스_기저귀
210037,20200805171023-18783441109,2020-08-06,20200805170229147688,체험팩,맘큐 허그박스,맘큐,베이비용품,기저귀,맘큐_기저귀
210038,20200805224157-34181488371,2020-08-06,20200805223526494551,기타,[먼치킨] 멀티 젖병솔 세트,먼치킨,베이비용품,수유용품,먼치킨_수유용품

In [ ]:
df_sales_new2 = df_sales_new.drop(['주문번호','물품대분류','상품명','브랜드명','물품분류','물품중분류','단순상품명'], axis=1)
df_sales_new2.drop_duplicates(inplace=True)
df_sales_new2

               구매일                  고객번호
0       2019-05-06       201812310749735
1       2020-02-20       201812310749735
2       2019-02-28       201812310749770
3       2019-05-13       201812310749771
5       2019-05-10       201812310749774
...            ...                   ...
210034  2020-07-24  20200724113017315991
210035  2020-07-29  20200729134409126553
210036  2020-08-03  20200803075905757887
210037  2020-08-06  20200805170229147688
210038  2020-08-06  20200805223526494551

[178295 rows x 2 columns]

In [ ]:
w1 = df_sales_new.groupby(['고객번호','구매일'])['단순상품명'].apply(list)

In [ ]:
for i in w1:
    for j in i:
        if i.count(j) >= 2:
            i.remove(j)

In [ ]:
w1.shape

(178295,)

In [ ]:
cnt = 0
for i in a:
    cnt += 1
    
print(cnt)

2811

In [ ]:
df_sales_new2 = pd.merge(df_sales_new2, w1, how = 'left', on = ['구매일','고객번호'])
df_sales_new2

               구매일                  고객번호           단순상품명
0       2019-05-06       201812310749735     [더블하트_수유용품]
1       2020-02-20       201812310749735       [하기스_기저귀]
2       2019-02-28       201812310749770    [크리넥스_휴지/티슈]
3       2019-05-13       201812310749771       [하기스_기저귀]
4       2019-05-10       201812310749774       [하기스_기저귀]
...            ...                   ...             ...
178290  2020-07-24  20200724113017315991  [크리넥스_키친타올/행주]
178291  2020-07-29  20200729134409126553        [맘큐_기저귀]
178292  2020-08-03  20200803075905757887       [하기스_기저귀]
178293  2020-08-06  20200805170229147688        [맘큐_기저귀]
178294  2020-08-06  20200805223526494551      [먼치킨_수유용품]

[178295 rows x 3 columns]

In [ ]:
df_sales_new2.to_csv('고객번호_구매일 별 구매상품.csv', encoding='utf-8-sig')

In [ ]:
for

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
178290   NaN
178291   NaN
178292   NaN
178293   NaN
178294   NaN
Name: 단순상품명, Length: 178295, dtype: float64

In [ ]:
df_sales_new2['key'] = df_sales_new['구매일']+ '_' + df_sales_new['고객번호'].astype('string')
keys = list(df_sales_new['구매일']+ '_' + df_sales_new['고객번호'].astype('string'))

In [ ]:
df_sales_new2.to_csv('고객번호_구매일별 구매 상품.csv', encoding='utf-8-sig')